version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/cubist-node-sdk" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
