/// Auto-generated by Cubist. Do not edit manually.
import {
  Config,
  ContractFactory,
  Cubist,
  Target,
} from '@cubist-alpha/cubist';

// Export targets

export const Avalanche = Target.Avalanche;
export const Ethereum = Target.Ethereum;
export const Polygon = Target.Polygon;

/** Project-specific CubistORM. */
export class CubistORM extends Cubist {
  /** Create new project per target
   * @param {Config?} config - Optional config (using near otherwise).
   */
  constructor(config) {
    super(config);
  }

{%- for c in contracts %}
  /** Get contract factory for {{c}}
   * @return {ContractFactory} - The contract factory.
   */
  get {{c}}() {
    return this.getContractFactory('{{c}}');
  }
{% endfor %}
}
