name: Close PRs

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches: [ "main" ]

jobs:
  close-prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-pr-stale: 0
          days-before-close: 0
          days-before-pr-close: 0
          close-pr-message: "This is a mirror. Please submit your PRs to https://github.com/cubist-labs/cubist"
